// Angular-Learning/Angular-Learning-notes+practice/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
 constructor(private router:Router){

 }

  LearningAngular(){
  this.router.navigateByUrl("/LearningAngular")
  }
}

<div class="Main-Container">
  <button (click)="LearningAngular()">LearningAngular</button>
<div class="Container">
    <h4>LogIn Form Component</h4>
    <form>
      Username : <input type="text" placeholder="Enter Username or Phone No" > 
       
      password : <input type="password" placeholder="Enter Password">
      <button>LogIn</button>
      
    </form>
  </div>
</div>

// Learn_React-Start/src/loginComponents/Login.js
import React from 'react'
import Input from './Input'

export default function Login() {
  return (
    <form className="form">
        <Input type="text" placeholder="Username"/>
        <Input type="password" placeholder="Password"/> 
        {/* <Input type="password" placeholder="Confirm Password"/>  */}
    <button type='submit'>Login</button>
    {/* <button type='submit'>Register</button> */}
</form>
  )
}
